# Generated by Django 3.2 on 2022-12-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
                ('main_text', models.CharField(max_length=200)),
                ('second_text', models.CharField(max_length=200)),
                ('third_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('active_starus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=10000)),
                ('time', models.CharField(max_length=10000)),
                ('availability', models.CharField(max_length=10000)),
                ('min_age', models.CharField(max_length=10000)),
                ('max_people', models.CharField(max_length=10000)),
                ('tour_details', models.CharField(max_length=10000)),
                ('itinerary', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=10000)),
                ('images', models.CharField(max_length=10000)),
                ('tour_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.tourcategory')),
                ('tour_location', models.ManyToManyField(to='adminpanel.TourLocation')),
            ],
        ),
    ]
