# Generated by Django 3.2 on 2022-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcategory',
            name='active_starus',
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='order',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
