# Generated by Django 3.2 on 2022-12-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20221211_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='availability',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='min_age',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_details',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=10000000),
        ),
    ]
