# Generated by Django 3.2 on 2022-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20221211_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ImageField(upload_to='image_images'),
        ),
    ]
