# Generated by Django 3.2 on 2022-12-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20221211_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourImage',
        ),
        migrations.AddField(
            model_name='tour',
            name='images',
            field=models.FileField(default='Null', upload_to=''),
            preserve_default=False,
        ),
    ]
