# Generated by Django 3.2 on 2022-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20221211_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
        migrations.AddField(
            model_name='tour',
            name='featured_image',
            field=models.ImageField(default='null', upload_to='tour_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image1',
            field=models.ImageField(default='null', upload_to='tour_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image2',
            field=models.ImageField(default='null', upload_to='tour_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image3',
            field=models.ImageField(default='null', upload_to='tour_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image4',
            field=models.ImageField(default='null', upload_to='tour_image'),
            preserve_default=False,
        ),
    ]
