# Generated by Django 3.2 on 2022-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20221211_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='custom_url',
            field=models.URLField(default='https://www.facebook.com/'),
            preserve_default=False,
        ),
    ]
