# Generated by Django 3.2 on 2022-12-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_slider_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='custom_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
