# Generated by Django 3.2 on 2022-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20221211_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='order',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
