# Generated by Django 3.2 on 2022-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20221211_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourLocation',
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_location',
            field=models.ManyToManyField(to='adminpanel.Destination'),
        ),
    ]
