# Generated by Django 3.2 on 2022-12-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_auto_20221211_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tour_image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tour_image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tour_image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='tour_image'),
        ),
    ]
