# Generated by Django 3.2 on 2022-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20221211_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
