# Generated by Django 3.2 on 2022-12-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=5000)),
                ('star', models.IntegerField()),
                ('image', models.ImageField(upload_to='testimonial_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '  Slider'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name_plural': ' TourCategory'},
        ),
    ]
