# Generated by Django 3.2 on 2022-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_auto_20221211_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='star',
            field=models.PositiveIntegerField(),
        ),
    ]
