# Generated by Django 3.2 on 2022-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image4',
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_location',
            field=models.ManyToManyField(blank=True, null=True, to='adminpanel.Destination'),
        ),
    ]
