# Generated by Django 3.2 on 2022-12-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_auto_20221213_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_location',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.destination'),
        ),
    ]
