# Generated by Django 3.2 on 2022-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_tour_offered_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('position', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='team_images')),
            ],
        ),
    ]
