# Generated by Django 3.2 on 2022-12-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_auto_20221213_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
    ]
