# Generated by Django 3.2 on 2022-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_blog_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
