# Generated by Django 3.2 on 2022-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.IntegerField()),
                ('header_logo', models.ImageField(upload_to='company_images')),
                ('footer_logo', models.ImageField(upload_to='company_images')),
                ('location', models.CharField(max_length=1000)),
                ('primary_contact', models.CharField(max_length=1000)),
                ('secondary_contact', models.CharField(max_length=1000)),
                ('primary_email', models.CharField(max_length=1000)),
                ('secondary_email', models.CharField(max_length=1000)),
                ('opening_hours', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=100)),
                ('tour_packages', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('happy_customers', models.CharField(max_length=100)),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('twitter_url', models.URLField()),
            ],
        ),
    ]
