# Generated by Django 3.2 on 2022-12-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_companysetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetup',
            name='data_set',
            field=models.CharField(max_length=100),
        ),
    ]
