# Generated by Django 3.2 on 2022-12-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name_plural': '    Tours & Trekking'},
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='offered_price',
            new_name='drop_location',
        ),
    ]
