# Generated by Django 3.2 on 2022-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_auto_20221220_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
