# Generated by Django 3.2 on 2022-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_alter_tour_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetup',
            name='about_us_page_content',
            field=models.CharField(default='feaf', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysetup',
            name='about_us_page_heading_text',
            field=models.CharField(default='awda', max_length=100000),
            preserve_default=False,
        ),
    ]
