# Generated by Django 3.2 on 2022-12-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_auto_20221220_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
