# Generated by Django 3.2 on 2022-12-23 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.TextField()),
                ('header_logo', models.ImageField(upload_to='company_images')),
                ('footer_logo', models.ImageField(upload_to='company_images')),
                ('location', models.TextField()),
                ('primary_contact', models.TextField()),
                ('secondary_contact', models.TextField()),
                ('primary_email', models.TextField()),
                ('secondary_email', models.TextField()),
                ('opening_hours', models.TextField()),
                ('years_of_experience', models.TextField()),
                ('tour_packages', models.TextField()),
                ('happy_customers', models.TextField()),
                ('destination', models.TextField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('about_us_page_heading_text', models.TextField()),
                ('about_us_page_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('contact', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('image', models.ImageField(upload_to='destination_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.ImageField(upload_to='partner_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('image', models.ImageField(upload_to='team_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('name', models.TextField()),
                ('star', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(upload_to='testimonial_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('order', models.PositiveIntegerField(default='1')),
                ('is_active', models.BooleanField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': ' TourCategory',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.TextField()),
                ('drop_location', models.TextField(blank=True, null=True)),
                ('time', models.TextField()),
                ('availability', models.TextField()),
                ('min_age', models.TextField()),
                ('max_people', models.TextField()),
                ('tour_details', models.TextField()),
                ('itinerary', models.TextField()),
                ('price', models.TextField()),
                ('featured_image', models.ImageField(upload_to='tour_image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='tour_image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='tour_image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='tour_image')),
                ('is_featured', models.BooleanField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('tour_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller.tourcategory')),
                ('tour_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traveller.destination')),
            ],
            options={
                'verbose_name_plural': '    Tours & Trekking',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('contact', models.TextField()),
                ('no_of_travellers', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller.tour')),
            ],
        ),
    ]
