# Generated by Django 3.2 on 2022-12-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='custom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
